from refactor_parser import RefactorParser
from ewas_parser import EWASParser
from methylation_data_parser import MethylationDataParser
from module_parser import ModuleParser
from kit_parser import KitParser
from predictor_parser import PredictorParser